version: '3.1'
services:
  web:
    image: "ustcgxd/web"
    ports:
      - "3838:3838"
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    image: "ustcgxd/api"
    ports:
      - "80:80"
      - "8004:8004"
