version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    image: "ustcgxd/web"
    ports:
      - "3838:3838"
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

